## NumPy

__Question 1:__
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np

In [2]:
a = np.random.choice(10, 10, replace=False)
b = np.round([0.121, 1.26253, 1.0041, 3, 2, 5, 2.1341, 7.234, 8.8762, 9], decimals=1)

print(a)
print(b)
print(np.greater(a, b),'\n')
print(np.greater_equal(a, b),'\n')
print(np.less(a, b),'\n')
print(np.less_equal(a, b),'\n')

[3 4 5 8 7 0 2 6 1 9]
[0.1 1.3 1.  3.  2.  5.  2.1 7.2 8.9 9. ]
[ True  True  True  True  True False False False False False] 

[ True  True  True  True  True False False False False  True] 

[False False False False False  True  True  True  True False] 

[False False False False False  True  True  True  True  True] 



__Question 2:__
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [3]:
x = np.zeros(10, np.int)
print(x,'\n')

y = np.ones(10, np.int)
print(y,'\n')

z = np.ones(10, np.int)*5
print(z)

[0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 1 1 1] 

[5 5 5 5 5 5 5 5 5 5]


__Question 3:__
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [8]:
array = np.random.choice(18, 42, replace=True).reshape(6,7)
print(array,'\n')

print("Columnwise addition => ",np.sum(array, axis=0),'\n')
print('Rowwise addition => ',np.sum(array, axis=1))

[[10  5  6  5 17  3  4]
 [11  3 12  5 16 16  4]
 [ 8 13 13 17 17  0  5]
 [ 6 11 12  3 13  5 12]
 [14  2  9 13  5  6 14]
 [ 5  1 12  1  4 12  8]] 

Columnwise addition =>  [54 35 64 44 72 42 47] 

Rowwise addition =>  [50 67 73 62 63 43]


__Question 4:__
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [10]:
array1 = np.array([[1,1022,8],[69,132,287]])
array2 = np.array([[100,2020,57],[46,89,865]])

print("Addition",np.add(array1,array2))


print("Subtraction",np.subtract(array1,array2))  


print("multiplication",np.multiply(array1,array2))

print("division",np.divide(array1,array2))

Addition [[ 101 3042   65]
 [ 115  221 1152]]
Subtraction [[ -99 -998  -49]
 [  23   43 -578]]
multiplication [[    100 2064440     456]
 [   3174   11748  248255]]
division [[0.01       0.50594059 0.14035088]
 [1.5        1.48314607 0.33179191]]


__Question 5:__
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [12]:
print("sine\n")
print(np.sin(np.array((0, 30, 45, 60, 90))))

print("\n cosine: \n")
print(np.cos(np.array((0, 30, 45, 60, 90))))

print("\ntangent:\n" )
print(np.tan(np.array((0., 30., 40., 45., 75., 180., 360.))))

sine

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]

 cosine: 

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]

tangent:

[ 0.         -6.4053312  -1.11721493  1.61977519 -0.42070095  1.33869021
 -3.38014041]
